before_script:
  - apt-get update -qq && apt-get install -y -qq wget 
  - git remote set-url origin https://USERNAME:${CI_PUSH_TOKEN}@gitlab.com/thetorproject/gettorbrowser.git
  - git remote add github https://${SECURE_TOKEN}@github.com/TheTorProject/gettorbrowser.git
  - git config --global user.email 'silvia@nopressure.co.uk'
  - git config --global user.name 'hiromipaw'

job:
  script: |
    git checkout -B releases
    rm -f torbrowser-* TorBrowser-* tor-browser-*
    
    content=$(wget https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions/ -q -O -) && \
    temp="${content//\"}" && temp="${temp//\[}" && temp="${temp//\]}" && \
    arr=(`echo ${temp//,}`) && alpha="${arr[@]: 4:1}" && version="${arr[@]: 0:1}"
    
    locales=(en-US es-ES pt-BR)
    for i in "${locales[@]}" 
    do 
        wget https://www.torproject.org/dist/torbrowser/$version/torbrowser-install-$version\_$i.exe     
        wget https://www.torproject.org/dist/torbrowser/$version/torbrowser-install-win64-$version\_$i.exe.asc
        wget https://www.torproject.org/dist/torbrowser/$version/TorBrowser-$version-osx64_$i.dmg
        wget https://www.torproject.org/dist/torbrowser/$version/TorBrowser-$version-osx64_$i.dmg.asc
        wget https://www.torproject.org/dist/torbrowser/$version/tor-browser-linux32-$version\_$i.tar.xz
        wget https://www.torproject.org/dist/torbrowser/$version/tor-browser-linux32-$version\_$i.tar.xz.asc
        wget https://www.torproject.org/dist/torbrowser/$version/tor-browser-linux64-$version\_$i.tar.xz
        wget https://www.torproject.org/dist/torbrowser/$version/tor-browser-linux64-$version\_$i.tar.xz.asc
        
        wget https://www.torproject.org/dist/torbrowser/$alpha/torbrowser-install-$alpha\_$i.exe     
        wget https://www.torproject.org/dist/torbrowser/$alpha/torbrowser-install-win64-$alpha\_$i.exe.asc
        wget https://www.torproject.org/dist/torbrowser/$alpha/TorBrowser-$alpha-osx64_$i.dmg
        wget https://www.torproject.org/dist/torbrowser/$alpha/TorBrowser-$alpha-osx64_$i.dmg.asc
        wget https://www.torproject.org/dist/torbrowser/$alpha/tor-browser-linux32-$alpha\_$i.tar.xz
        wget https://www.torproject.org/dist/torbrowser/$alpha/tor-browser-linux32-$alpha\_$i.tar.xz.asc
        wget https://www.torproject.org/dist/torbrowser/$alpha/tor-browser-linux64-$alpha\_$i.tar.xz
        wget https://www.torproject.org/dist/torbrowser/$alpha/tor-browser-linux64-$alpha\_$i.tar.xz.asc
    done
    
    git add .
    git commit -m '[dist ci] commit from CI runner - update with new torbrowser downloads'
    diffs=$(git diff origin/releases)
    if [ -z "$diffs" ]; then
        echo "No new releases"
    else
        git push -f --follow-tags origin releases
    fi
    
    git fetch --all
    git checkout -b torbrowser-releases

    diffs=$(git diff github/torbrowser-releases)
    if [ -z "$diffs" ]; then
        echo "No new releases"
    else
        git push -f --follow-tags github torbrowser-releases
    fi
    